import type { AnalysisSummary } from "./types";

const miranaCandidate = {
  id: "hk-028",
  rank: 1,
  kind: "hero_kill_sequence",
  title: "npc_dota_hero_mirana kill sequence (3)",
  score: 168,
  start_seconds: 1093.4,
  peak_seconds: 1116.1667,
  end_seconds: 1119.1667,
  hero_deaths: 3,
  anchor_tick: 32826,
  primary_hero: "npc_dota_hero_mirana",
  participants: [
    "npc_dota_hero_mirana",
    "npc_dota_hero_snapfire",
    "npc_dota_hero_ogre_magi",
    "npc_dota_hero_earthshaker",
  ],
  reasons: [
    "Mirana received credit for three hero kills in one continuous sequence.",
  ],
  kill_sequence: {
    hero: "npc_dota_hero_mirana",
    sequence_index: 1,
    sequence_count: 8,
    total_kills: 12,
    kills: [
      {
        death_tick: 32212,
        death_time_seconds: 1095.7001,
        target_hero: "npc_dota_hero_snapfire",
        inflictor: "mirana_starfall",
        setup_tick: 32172,
        setup_time_seconds: 1094.4,
        setup_action: "mirana_starfall",
      },
      {
        death_tick: 32670,
        death_time_seconds: 1110.9667,
        target_hero: "npc_dota_hero_ogre_magi",
        inflictor: "mirana_arrow",
        setup_tick: 32656,
        setup_time_seconds: 1110.5,
        setup_action: "mirana_arrow",
      },
      {
        death_tick: 32826,
        death_time_seconds: 1116.1667,
        target_hero: "npc_dota_hero_earthshaker",
        setup_tick: 32656,
        setup_time_seconds: 1110.5,
        setup_action: "mirana_arrow",
      },
    ],
  },
};

export const miranaDevelopmentSummary: AnalysisSummary = {
  job_id: "d2h-development-mirana",
  job_dir: "C:\\Dota2Highlights\\fixtures\\mirana-story",
  source: {
    path: "C:\\Dota2\\replays\\mirana-story.dem",
    byte_length: 1,
    sha256: "development-fixture",
    magic: "PBDEMS2",
  },
  replay: {
    playback_ticks: 89904,
    playback_time_seconds: 2996.8,
    game_build: 1,
    match_id: 1234567890,
    game_mode: 22,
    game_winner: 2,
    players: [
      {
        slot: 0,
        hero_name: "npc_dota_hero_earthshaker",
        game_team: 2,
        is_fake_client: false,
      },
      {
        slot: 1,
        hero_name: "npc_dota_hero_slark",
        game_team: 2,
        is_fake_client: false,
      },
      {
        slot: 2,
        hero_name: "npc_dota_hero_snapfire",
        game_team: 2,
        is_fake_client: false,
      },
      {
        slot: 3,
        hero_name: "npc_dota_hero_ogre_magi",
        game_team: 2,
        is_fake_client: false,
      },
      {
        slot: 4,
        hero_name: "npc_dota_hero_tidehunter",
        game_team: 2,
        is_fake_client: false,
      },
      {
        slot: 5,
        hero_name: "npc_dota_hero_luna",
        game_team: 3,
        is_fake_client: false,
      },
      {
        slot: 6,
        hero_name: "npc_dota_hero_undying",
        game_team: 3,
        is_fake_client: false,
      },
      {
        slot: 7,
        hero_name: "npc_dota_hero_ancient_apparition",
        game_team: 3,
        is_fake_client: false,
      },
      {
        slot: 8,
        hero_name: "npc_dota_hero_lion",
        game_team: 3,
        is_fake_client: false,
      },
      {
        slot: 9,
        hero_name: "npc_dota_hero_mirana",
        game_team: 3,
        is_fake_client: false,
      },
    ],
  },
  event_count: 1200,
  highlights: {
    schema_version: "1.4",
    source_sha256: "development-fixture",
    detector: {
      name: "rules-v2",
      version: "0.5.0",
    },
    candidates: [miranaCandidate],
  },
  stories: {
    schema_version: "1.2",
    source_sha256: "development-fixture",
    detector: {
      name: "rules-v2",
      version: "0.5.0",
    },
    stories: [
      {
        id: "story-skill-hk-028",
        rank: 1,
        category: "skill",
        template_id: "hero_kill_sequence_v1",
        title: "mirana confirmed kill sequence (3 kills)",
        primary_hero: "npc_dota_hero_mirana",
        participants: [
          {
            hero: "npc_dota_hero_mirana",
            role: "protagonist",
          },
          {
            hero: "npc_dota_hero_snapfire",
            role: "target",
          },
          {
            hero: "npc_dota_hero_ogre_magi",
            role: "target",
          },
          {
            hero: "npc_dota_hero_earthshaker",
            role: "target",
          },
        ],
        candidate_ids: ["hk-028"],
        source_start_seconds: 1093.4,
        source_peak_seconds: 1116.1667,
        source_end_seconds: 1119.1667,
        priority_score: 214,
        confidence: {
          level: "high",
          score: 0.97,
          reasons: [
            "Every payoff is a replay-attributed hero death.",
            "All kills have an explicit setup action.",
          ],
        },
        review_required: false,
        evidence: [
          {
            id: "mirana-setup-1",
            kind: "trigger",
            candidate_id: "hk-028",
            tick: 32172,
            time_seconds: 1094.4,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_snapfire",
            action: "mirana_starfall",
            detail: "Starfall begins the sequence.",
          },
          {
            id: "mirana-kill-1",
            kind: "kill",
            candidate_id: "hk-028",
            tick: 32212,
            time_seconds: 1095.7001,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_snapfire",
            action: "mirana_starfall",
            detail: "First confirmed kill.",
          },
          {
            id: "mirana-setup-2",
            kind: "trigger",
            candidate_id: "hk-028",
            tick: 32656,
            time_seconds: 1110.5,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_ogre_magi",
            action: "mirana_arrow",
            detail: "Sacred Arrow begins the final chain.",
          },
          {
            id: "mirana-kill-2",
            kind: "kill",
            candidate_id: "hk-028",
            tick: 32670,
            time_seconds: 1110.9667,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_ogre_magi",
            action: "mirana_arrow",
            detail: "Second confirmed kill.",
          },
          {
            id: "mirana-setup-3",
            kind: "trigger",
            candidate_id: "hk-028",
            tick: 32656,
            time_seconds: 1110.5,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_earthshaker",
            action: "mirana_arrow",
            detail: "The same arrow chain continues.",
          },
          {
            id: "mirana-kill-3",
            kind: "kill",
            candidate_id: "hk-028",
            tick: 32826,
            time_seconds: 1116.1667,
            actor: "npc_dota_hero_mirana",
            target: "npc_dota_hero_earthshaker",
            action: "mirana_arrow",
            detail: "Third confirmed kill.",
          },
        ],
        beats: [
          {
            id: "mirana-beat-setup",
            kind: "setup",
            source_start_seconds: 1093.4,
            source_end_seconds: 1094.4,
            summary: "Player-view context.",
            evidence_ids: ["mirana-setup-1"],
          },
          {
            id: "mirana-beat-development",
            kind: "development",
            source_start_seconds: 1094.4,
            source_end_seconds: 1096.95,
            summary: "Starfall confirms the first kill.",
            evidence_ids: ["mirana-setup-1", "mirana-kill-1"],
          },
          {
            id: "mirana-beat-payoff",
            kind: "payoff",
            source_start_seconds: 1110.5,
            source_end_seconds: 1117.4167,
            summary: "Arrow chain confirms two more kills.",
            evidence_ids: [
              "mirana-setup-2",
              "mirana-kill-2",
              "mirana-setup-3",
              "mirana-kill-3",
            ],
          },
        ],
        shots: [
          {
            id: "mirana-shot-01",
            order: 1,
            take_group_id: "story-skill-hk-028-take-sequence",
            take_role: "primary",
            include_in_default_cut: true,
            beat_id: "mirana-beat-setup",
            candidate_id: "hk-028",
            source_start_seconds: 1093.4,
            source_end_seconds: 1119.1667,
            camera_mode: "player_perspective",
            target_hero: "npc_dota_hero_mirana",
            framing: "normal_gameplay",
            purpose: "Keep the full sequence continuous.",
            fallback: {
              camera_mode: "player_perspective",
              target_hero: "npc_dota_hero_mirana",
              reason: "Player view is the safe shot.",
            },
          },
          {
            id: "mirana-shot-02",
            order: 2,
            take_group_id: "story-skill-hk-028-take-sequence",
            take_role: "alternate",
            include_in_default_cut: false,
            beat_id: "mirana-beat-payoff",
            candidate_id: "hk-028",
            source_start_seconds: 1093.4,
            source_end_seconds: 1119.1667,
            camera_mode: "hero_chase",
            target_hero: "npc_dota_hero_earthshaker",
            framing: "close_action",
            purpose: "Provide a synchronized close take for the final arrow impact.",
            fallback: {
              camera_mode: "player_perspective",
              target_hero: "npc_dota_hero_mirana",
              reason: "Return to Mirana if the target cannot be framed.",
            },
          },
        ],
        switch_windows: [
          {
            take_group_id: "story-skill-hk-028-take-sequence",
            alternate_shot_id: "mirana-shot-02",
            source_start_seconds: 1114.9167,
            source_end_seconds: 1117.6667,
            reason: "The close take can replace the main angle around the final arrow impact.",
          },
        ],
        reasons: [
          "Three kills remain in one continuous engagement.",
          "Two arrow-related payoffs support a technical edit.",
        ],
      },
    ],
  },
  director: {
    schema_version: "1.4",
    source_sha256: "development-fixture",
    template: "comic_hype_v1",
    total_duration_seconds: 25.7667,
    transition_seconds: 0.35,
    segments: [
      {
        candidate_id: "hk-028",
        source_start_seconds: 1093.4,
        source_peak_seconds: 1116.1667,
        source_peak_tick: 32826,
        source_end_seconds: 1119.1667,
        output_start_seconds: 0,
        output_end_seconds: 25.7667,
        primary_hero: "npc_dota_hero_mirana",
        score: 168,
        narration_hint: "",
        beats: [],
      },
    ],
    audio: {
      music_role: "none",
      bpm_min: 0,
      bpm_max: 0,
      game_audio_duck_db: 0,
      music_duck_under_voice_db: 0,
      cues: [],
    },
  },
  reused_existing_job: true,
};
